In [2]:
import torch as torch

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)


In [4]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)


tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])


In [18]:
#other common initialization methods

x = torch.empty(size = (3,3)) #(uninitialzed data)
x = torch.zeros((3,3))
x = torch.rand((3,3))
x = torch.ones((3,3))
x = torch.eye(5,5)
x = torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [27]:
#how to initialize and convert tensor to ohter types
tensor = torch.arange(4) #4 is the end value
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half()) #float 16
print(tensor.float()) #float 32
print(tensor.double()) #float 64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
<class 'torch.Tensor'>
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0, 1, 2, 3])


In [33]:
# array to tensor conversion and vice-versa
import numpy as np
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
# tensor.numpy to bring array back

In [34]:
y = torch.tensor([9,8,7])
z = torch.true_divide(x, y)

RuntimeError: The size of tensor a (5) must match the size of tensor b (3) at non-singleton dimension 0

In [ ]:
#inplace operations are computationally more efficient.
# t = t + x is going to create a copy first.
# t.add_(x) is the same as t+=x

#exoponentiation
#z = x.pow(2) or x**2