In [1]:
import numpy as np

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dot(a,b)
print(c)
print(a)
print(a.transpose())
d = np.dot(a.transpose(),b)
print(d)

32
[1 2 3]
[1 2 3]
32


In [13]:
a = np.random.randn(3,3)
print(a)
b = np.random.randn(3,1)
print(b)
c = a*b
print(c)

[[-0.46826616  0.01946276 -0.31139887]
 [ 0.31416874  0.64931812  0.73915512]
 [ 0.98161041  2.25536579 -0.72555746]]
[[-1.06942493]
 [ 0.94473577]
 [-1.11601722]]
[[ 0.5007755  -0.02081396  0.33301771]
 [ 0.29680645  0.61343405  0.69830628]
 [-1.09549413 -2.51702707  0.80973462]]


: 